### ISSUE TITLE
Issues starting the bot

### ISSUE THREAD

**Issue by degupukas** [rhiever/reddit-twitter-bot#23]
Hi, whenever I run the bot I just get this spit back at me.

I installed tweepy and praw

I set up my correct API keys for the app

and I've picked the subreddit I wanted

Any help is appreciated, thank you!
pi@raspberrypi:~/reddit-twitter-bot $ python reddit_twitter_bot.py
Traceback (most recent call last):
  File "reddit_twitter_bot.py", line 21, in <module>
    import praw
ImportError: No module named praw
pi@raspberrypi:~/reddit-twitter-bot $ python3 reddit_twitter_bot.py
[bot] Setting up connection with reddit
Traceback (most recent call last):
  File "/usr/lib/python3.7/configparser.py", line 845, in items
    d.update(self._sections[section])
KeyError: 'reddit Twitter tool monitoring r/ADSB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reddit_twitter_bot.py", line 192, in <module>
    main()
  File "reddit_twitter_bot.py", line 183, in main
    subreddit = setup_connection_reddit(SUBREDDIT_TO_MONITOR)
  File "reddit_twitter_bot.py", line 60, in setup_connection_reddit
    reddit_api = praw.Reddit('reddit Twitter tool monitoring {}'.format(subreddit))
  File "/home/pi/.local/lib/python3.7/site-packages/praw/reddit.py", line 228, in __init__
    config_section, config_interpolation, **config_settings
  File "/home/pi/.local/lib/python3.7/site-packages/praw/config.py", line 84, in __init__
    self.custom = dict(Config.CONFIG.items(site_name), **settings)
  File "/usr/lib/python3.7/configparser.py", line 848, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'reddit Twitter tool monitoring r/ADSB'
You provided the name of a praw.ini configuration which does not exist.

For help with creating a Reddit instance, visit
https://praw.readthedocs.io/en/latest/code_overview/reddit_instance.html

For help on configuring PRAW, visit
https://praw.readthedocs.io/en/latest/getting_started/configuration.html

**Comment by mitesh1691** [comment]
Did you find any solution?
